export const SET_INGREDIENT_IN_MODAL = "SET_INGREDIENT_IN_MODAL";
export const DEL_INGREDIENT_IN_MODAL = "DEL_INGREDIENT_IN_MODAL";
export const TOGGLE_MODAL_INGREDIENT = "TOGGLE_MODAL_INGREDIENT";
export const TOGGLE_MODAL_ORDER = "TOGGLE_MODAL_ORDER";