export const ADD_BUN_IN_CONSTRUCTOR = "ADD_BUN_IN_CONSTRUCTOR";
export const ADD_IN_CONSTRUCTOR = "ADD_IN_CONSTRUCTOR";
export const DEL_IN_CONSTRUCTOR = "DEL_IN_CONSTRUCTOR";
export const DND_CONSTRUCTOR = "DND_CONSTRUCTOR";
export const TOTAL_PRICE = "TOTAL_PRICE";
export const RESET_CONSTRUCTOR = "RESET_CONSTRUCTOR" 