export const ADD_BUN_IN_CONSTRUCTOR = "ADD_BUN_IN_CONSTRUCTOR";
export const ADD_IN_CONSTRUCTOR = "ADD_IN_CONSTRUCTOR";
export const DEL_IN_CONSTRUCTOR = "DEL_IN_CONSTRUCTOR";
export const RESET_CONSTRUCTOR = "RESET_CONSTRUCTOR";
export const REPLACE_INGREDIENT = 'REPLACE_INGREDIENT';